name: Build

on: [push]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.welcome=never"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 17

      - name: Build Base API
        run: ./gradlew build

      - name: Publish to Maven Repository
        if: ${{ success() && github.repository == 'GeyserMC/api' }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_geysermcUsername: ${{ vars.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_geysermcPassword: ${{ secrets.DEPLOY_PASS }}

      - name: Notify Discord
        uses: Tim203/actions-git-discord-webhook@main
        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/api'}}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}